version: 2

models:
  - name: stg_stock_data
    description: "Staging model for stock data with data quality checks"
    columns:
      - name: symbol
        description: "Stock ticker symbol"
        tests:
          - not_null
          - accepted_values:
              values: ['AAPL', 'GOOG']
      - name: date
        description: "Trading date"
        tests:
          - not_null
      - name: close
        description: "Closing price"
        tests:
          - not_null

  - name: moving_averages
    description: "Moving averages calculations (7, 14, 30, 50 day)"
    columns:
      - name: symbol
        tests:
          - not_null
      - name: date
        tests:
          - not_null
      - name: sma_7
        description: "7-day simple moving average"
      - name: sma_14
        description: "14-day simple moving average"
      - name: sma_30
        description: "30-day simple moving average"
      - name: sma_50
        description: "50-day simple moving average"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - symbol
            - date

  - name: rsi
    description: "Relative Strength Index (14-period)"
    columns:
      - name: symbol
        tests:
          - not_null
      - name: date
        tests:
          - not_null
      - name: rsi_14
        description: "14-period RSI"
        tests:
          - not_null
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - symbol
            - date

  - name: stock_analytics_mart
    description: "Combined analyticsmart with MA and RSI signals"
    columns:
      - name: symbol
        tests:
          - not_null
      - name: date
        tests:
          - not_null
      - name: combined_signal
        description: "Combined trading signal based on RSI and MA"
        tests:
          - accepted_values:
              values: ['STRONG_BUY', 'BUY', 'HOLD', 'SELL', 'STRONG_SELL', 'NEUTRAL']